### ISSUE TITLE
Add supported extensions

### ISSUE THREAD

**Issue by dastrong-codiga** [codiga/jetbrains-plugin#213]
**Describe the bug**
We're missing some supported extensions in this plugin. 

You can review all the extensions in our [VSCode plugin](https://github.com/codiga/vscode-plugin/blob/main/src/utils/fileUtils.ts) and add the missing ones to this plugin, please. 

The missing ones are: `.ipynb` and `.dockerfile`

**Comment by juli1** [comment]
@dastrong-codiga for `.ipnb`, notebook are not opened with JetBrains AFAIK. For Dockerfile, please be careful, we must supper
`<prefix>.dockerfile`
`dockerfile.<suffix>`
`Dockerfile`
